runtime: python311 # or another supported version

instance_class: F2

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "google-credentials.json"

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
